// import {defineField, defineType} from 'sanity'

// export const itinerary = defineType({
//   name: 'itinerary',
//   title: 'Itinerary',
//   type: 'document',
//   fields: [
//     defineField({name: 'bookTitleES', title: 'Book Title (ES)', type: 'string'}),
//     defineField({name: 'updatedAt', title: 'Updated At', type: 'string'}),
//     defineField({name: 'priority', title: 'Priority', type: 'number'}),
//     defineField({
//       name: 'passenger',
//       title: 'Passenger',
//       type: 'object',
//       fields: [
//         defineField({name: 'max', title: 'Max', type: 'number'}),
//         defineField({name: 'min', title: 'Min', type: 'number'}),
//         defineField({name: 'mas', title: 'Mas', type: 'string'}),
//       ],
//     }),
//     defineField({name: 'b2b', title: 'B2B', type: 'boolean'}),
//     defineField({name: 'categoryId', title: 'Category Id', type: 'string'}),
//     defineField({name: 'estado', title: 'Estado', type: 'string'}),
//     defineField({
//       name: 'objCliente',
//       title: 'Objeto Cliente',
//       type: 'object',
//       fields: [
//         defineField({name: 'createdBy', title: 'Created By', type: 'string'}),
//         defineField({name: 'id', title: 'Cliente Id', type: 'string'}),
//       ],
//     }),
//     defineField({name: 'bookTitle', title: 'Book Title', type: 'string'}),
//     defineField({
//       name: 'notIncludedES',
//       title: 'No Incluye (ES)',
//       type: 'array',
//       of: [{type: 'string'}],
//     }),
//     defineField({name: 'tipoTemplate', title: 'Tipo Template', type: 'string'}),
//     defineField({
//       name: 'extraInformation',
//       title: 'Extra Information',
//       type: 'object',
//       fields: [
//         defineField({name: 'description', title: 'Description', type: 'text'}),
//         defineField({name: 'titleES', title: 'Title (ES)', type: 'string'}),
//         defineField({name: 'title', title: 'Title', type: 'string'}),
//         defineField({name: 'descriptionES', title: 'Description (ES)', type: 'text'}),
//       ],
//     }),
//     defineField({
//       name: 'included',
//       title: 'Incluye',
//       type: 'array',
//       of: [{type: 'string'}],
//     }),
//     defineField({name: 'galleryTitle', title: 'Gallery Title', type: 'string'}),
//     defineField({name: 'state', title: 'State', type: 'string'}),
//     defineField({
//       name: 'listOfDepartureDates',
//       title: 'List Of Departure Dates',
//       type: 'array',
//       of: [
//         {
//           type: 'object',
//           fields: [
//             defineField({name: 'date', title: 'Date', type: 'string'}),
//             defineField({
//               name: 'idsFilesHijos',
//               title: 'Ids Files Hijos',
//               type: 'array',
//               of: [{type: 'string'}],
//             }),
//             defineField({name: 'idFilePadre', title: 'Id File Padre', type: 'string'}),
//             defineField({name: 'isOpen', title: 'Is Open', type: 'boolean'}),
//             defineField({name: 'reservations', title: 'Reservations', type: 'number'}),
//             defineField({name: 'paxReservations', title: 'Pax Reservations', type: 'number'}),
//             defineField({name: 'permitsAvailable', title: 'Permits Available', type: 'number'}),
//           ],
//         },
//       ],
//     }),
//     defineField({name: 'nameClient', title: 'Nombre Cliente', type: 'string'}),
//     defineField({
//       name: 'whatToTakeES',
//       title: 'Llevar (ES)',
//       type: 'array',
//       of: [{type: 'string'}],
//     }),
//     defineField({
//       name: 'slugES',
//       title: 'Slug (ES)',
//       type: 'slug',
//       options: {source: 'nombre', maxLength: 96},
//     }),
//     defineField({
//       name: 'tags',
//       title: 'Tags',
//       type: 'array',
//       of: [{type: 'string'}],
//     }),
//     defineField({name: 'destino', title: 'Destino', type: 'string'}),
//     defineField({
//       name: 'whatToTake',
//       title: 'What To Take',
//       type: 'array',
//       of: [{type: 'string'}],
//     }),
//     defineField({name: 'diasItinerario', title: 'Dias Itinerario', type: 'number'}),
//     defineField({
//       name: 'daysActivitiesList',
//       title: 'Lista de Actividades por Dia',
//       type: 'array',
//       of: [
//         {
//           type: 'object',
//           fields: [
//             defineField({
//               name: 'mobilitys',
//               title: 'Mobilidades',
//               type: 'array',
//               of: [
//                 {
//                   type: 'object',
//                   fields: [
//                     defineField({
//                       name: 'distance',
//                       title: 'Distancia',
//                       type: 'object',
//                       fields: [
//                         defineField({name: 'double', title: 'Double', type: 'number'}),
//                         defineField({name: 'long', title: 'Long', type: 'number'}),
//                       ],
//                     }),
//                     defineField({name: 'type', title: 'Tipo', type: 'string'}),
//                     defineField({name: 'time', title: 'Tiempo', type: 'string'}),
//                   ],
//                 },
//               ],
//             }),
//             defineField({name: 'description', title: 'Descripcion', type: 'text'}),
//             defineField({name: 'titleES', title: 'Titulo (ES)', type: 'string'}),
//             defineField({name: 'title', title: 'Titulo', type: 'string'}),
//             defineField({name: 'descriptionES', title: 'Descripcion (ES)', type: 'text'}),
//             defineField({name: 'map', title: 'Mapa', type: 'string'}),
//           ],
//         },
//       ],
//     }),
//     defineField({name: 'clienteId', title: 'Cliente Id', type: 'string'}),
//     defineField({
//       name: 'productIds',
//       title: 'Product Ids',
//       type: 'array',
//       of: [{type: 'string'}],
//     }),
//     defineField({
//       name: 'slug',
//       title: 'Slug',
//       type: 'slug',
//       options: {source: 'nombre', maxLength: 96},
//     }),
//     defineField({name: 'color', title: 'Color', type: 'string'}),
//     defineField({
//       name: 'season',
//       title: 'Season',
//       type: 'object',
//       fields: [
//         defineField({name: 'start', title: 'Start', type: 'string'}),
//         defineField({name: 'end', title: 'End', type: 'string'}),
//       ],
//     }),
//     defineField({name: 'nombre', title: 'Nombre', type: 'string'}),
//     defineField({name: 'usuario', title: 'Usuario', type: 'string'}),
//     defineField({
//       name: 'includedES',
//       title: 'Incluye (ES)',
//       type: 'array',
//       of: [{type: 'string'}],
//     }),
//     defineField({name: 'availableDaysES', title: 'Dias Disponibles (ES)', type: 'string'}),
//     defineField({name: 'version', title: 'Version', type: 'string'}),
//     defineField({
//       name: 'notIncluded',
//       title: 'No Incluye',
//       type: 'array',
//       of: [{type: 'string'}],
//     }),
//     defineField({name: 'id', title: 'Id', type: 'string'}),
//     defineField({
//       name: 'itinerary',
//       title: 'Itinerary',
//       type: 'object',
//       fields: [
//         defineField({name: 'description', title: 'Description', type: 'text'}),
//         defineField({name: 'titleES', title: 'Title (ES)', type: 'string'}),
//         defineField({name: 'title', title: 'Title', type: 'string'}),
//         defineField({name: 'descriptionES', title: 'Description (ES)', type: 'text'}),
//       ],
//     }),
//     defineField({name: 'availableDays', title: 'Dias Disponibles', type: 'string'}),
//     defineField({name: 'updatedByUserId', title: 'Updated By User Id', type: 'string'}),
//     defineField({name: 'createdAt', title: 'Created At', type: 'string'}),
//     defineField({name: 'priceTag', title: 'Price Tag', type: 'number'}),
//     defineField({name: 'destinationId', title: 'Destination Id', type: 'string'}),
//     defineField({name: 'galleryTitleES', title: 'Gallery Title (ES)', type: 'string'}),
//     defineField({
//       name: 'imagesByDay',
//       title: 'Images By Day',
//       type: 'array',
//       of: [
//         {
//           type: 'object',
//           fields: [
//             defineField({name: 'name', title: 'Name', type: 'string'}),
//             defineField({name: 'productId', title: 'Product Id', type: 'string'}),
//             defineField({name: 'day', title: 'Day', type: 'number'}),
//           ],
//         },
//       ],
//     }),
//     defineField({
//       name: 'topBanner',
//       title: 'Top Banner',
//       type: 'object',
//       fields: [
//         defineField({name: 'description', title: 'Description', type: 'text'}),
//         defineField({
//           name: 'image',
//           title: 'Image',
//           type: 'object',
//           fields: [
//             defineField({name: 'alt', title: 'Alt', type: 'string'}),
//             defineField({name: 'src', title: 'Src', type: 'string'}),
//             defineField({name: 'srcMobile', title: 'Src Mobile', type: 'string'}),
//           ],
//         }),
//         defineField({name: 'titleES', title: 'Title (ES)', type: 'string'}),
//         defineField({name: 'title', title: 'Title', type: 'string'}),
//         defineField({name: 'descriptionES', title: 'Description (ES)', type: 'text'}),
//       ],
//     }),
//     defineField({name: 'updateAtPermits', title: 'Update At Permits', type: 'string'}),
//     defineField({name: 'editProductServices', title: 'Edit Product Services', type: 'string'}),
//     defineField({
//       name: 'tipoSalida',
//       title: 'Tipo de Salida',
//       type: 'array',
//       of: [{type: 'string'}],
//     }),
//     defineField({
//       name: 'metaTags',
//       title: 'Meta Tags',
//       type: 'object',
//       fields: [
//         defineField({name: 'description', title: 'Description', type: 'text'}),
//         defineField({name: 'titleES', title: 'Title (ES)', type: 'string'}),
//         defineField({
//           name: 'keywords',
//           title: 'Keywords',
//           type: 'array',
//           of: [{type: 'string'}],
//         }),
//         defineField({name: 'title', title: 'Title', type: 'string'}),
//         defineField({
//           name: 'keywordsES',
//           title: 'Keywords (ES)',
//           type: 'array',
//           of: [{type: 'string'}],
//         }),
//         defineField({name: 'descriptionES', title: 'Description (ES)', type: 'text'}),
//       ],
//     }),
//     defineField({
//       name: 'touristType',
//       title: 'Tourist Type',
//       type: 'array',
//       of: [{type: 'string'}],
//     }),
//     defineField({name: 'categoriaProducto', title: 'Categoria Producto', type: 'string'}),
//     defineField({
//       name: 'destinations',
//       title: 'Destinations',
//       type: 'array',
//       of: [{type: 'string'}],
//     }),
//     defineField({name: 'days', title: 'Days', type: 'number'}),
//     defineField({name: 'type', title: 'Type', type: 'string'}),
//     defineField({name: 'typeES', title: 'Type (ES)', type: 'string'}),
//     defineField({
//       name: 'incluyeIngles',
//       title: 'Incluye Ingles',
//       type: 'array',
//       of: [{type: 'string'}],
//     }),
//     defineField({
//       name: 'noIncluye',
//       title: 'No Incluye',
//       type: 'array',
//       of: [{type: 'string'}],
//     }),
//     defineField({
//       name: 'llevar',
//       title: 'Llevar',
//       type: 'array',
//       of: [{type: 'string'}],
//     }),
//     defineField({
//       name: 'noIncluyeIngles',
//       title: 'No Incluye Ingles',
//       type: 'array',
//       of: [{type: 'string'}],
//     }),
//     defineField({
//       name: 'llevarIngles',
//       title: 'Llevar Ingles',
//       type: 'array',
//       of: [{type: 'string'}],
//     }),
//     defineField({
//       name: 'incluye',
//       title: 'Incluye',
//       type: 'array',
//       of: [{type: 'string'}],
//     }),
//     defineField({name: 'estadoItinerario', title: 'Estado Itinerario', type: 'string'}),
//     defineField({
//       name: 'diasDisponible',
//       title: 'Dias Disponible',
//       type: 'array',
//       of: [{type: 'string'}],
//     }),
//     defineField({name: 'isPublished', title: 'Is Published', type: 'boolean'}),
//     defineField({
//       name: 'weeks',
//       title: 'Weeks',
//       type: 'object',
//       fields: [
//         defineField({name: 'fourth', title: 'Fourth', type: 'boolean'}),
//         defineField({name: 'third', title: 'Third', type: 'boolean'}),
//         defineField({name: 'first', title: 'First', type: 'boolean'}),
//         defineField({name: 'second', title: 'Second', type: 'boolean'}),
//       ],
//     }),
//   ],
// })
